version: "3.1"

services:
  spk_cli:
    image: mkenjis/ubspkcli_kfk_img
    ports:
      - 8082:8082
    networks:
      - mynet
    depends_on:
      - kfk1,kfk2,kfk3
  kfk1:
    image: mkenjis/ubkfk_img
    environment:
      - BROKER_ID=0
      - KFK_HOST=kfk1
      - ZKP_HOST_BROKERS=kfk1,kfk2,kfk3
    ports:
      - "9092:9092"
    networks:
      - mynet
  kfk2:
    image: mkenjis/ubkfk_img
    environment:
      - BROKER_ID=1
      - KFK_HOST=kfk2
      - ZKP_HOST_BROKERS=kfk1,kfk2,kfk3
    ports:
      - "9093:9092"
    networks:
      - mynet
  kfk3:
    image: mkenjis/ubkfk_img
    environment:
      - BROKER_ID=2
      - KFK_HOST=kfk3
      - ZKP_HOST_BROKERS=kfk1,kfk2,kfk3
    ports:
      - "9094:9092"
    networks:
      - mynet

networks:
  mynet:
